### ISSUE TITLE
Gen new version to include latest go-libp4dlog version at v0.9.6

### ISSUE THREAD

**Issue by jakeRM** [perforce/p4prometheus#17]
Hi,
Any chance you can generate a new version of the binary to include the latest release of the go-libp4dlog binary, which is now at v0.9.6? It has the MaxRunningCount bumped, which would help me out since I am running into that limit.

```
[jmillette@ussel-pfse002 ~]$ sudo systemctl status p4prometheus -l
● p4prometheus.service - P4prometheus
   Loaded: loaded (/etc/systemd/system/p4prometheus.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2021-06-07 19:47:02 PDT; 18h ago
  Process: 65155 ExecStart=/usr/local/bin/p4prometheus.linux-amd64 --config=/p4/common/config/p4prometheus.yml (code=exited, status=2)
 Main PID: 65155 (code=exited, status=2)

Jun 07 08:00:02 ussel-pfse002 p4prometheus.linux-amd64[65155]: time="2021-06-07T08:00:02-07:00" level=info msg="file was removed, closing and un-watching" fd=7 file=log
Jun 07 19:47:02 ussel-pfse002 p4prometheus.linux-amd64[65155]: panic: ERROR: max running command limit (10000) exceeded. Does this server log have completion records configured (configurable server=3)?
Jun 07 19:47:02 ussel-pfse002 p4prometheus.linux-amd64[65155]: goroutine 23 [running]:
Jun 07 19:47:02 ussel-pfse002 p4prometheus.linux-amd64[65155]: github.com/rcowham/go-libp4dlog.(*P4dFileParser).LogParser.func4(0xc0000e3800, 0x72e1e0, 0xc0000b5080)
Jun 07 19:47:02 ussel-pfse002 p4prometheus.linux-amd64[65155]: /Users/rcowham/go/pkg/mod/github.com/rcowham/go-libp4dlog@v0.9.5/p4dlog.go:1421 +0x2a7
Jun 07 19:47:02 ussel-pfse002 p4prometheus.linux-amd64[65155]: created by github.com/rcowham/go-libp4dlog.(*P4dFileParser).LogParser
Jun 07 19:47:02 ussel-pfse002 p4prometheus.linux-amd64[65155]: /Users/rcowham/go/pkg/mod/github.com/rcowham/go-libp4dlog@v0.9.5/p4dlog.go:1407 +0x174
Jun 07 19:47:02 ussel-pfse002 systemd[1]: p4prometheus.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 07 19:47:02 ussel-pfse002 systemd[1]: Unit p4prometheus.service entered failed state.
Jun 07 19:47:02 ussel-pfse002 systemd[1]: p4prometheus.service failed.
```

**Comment by rcowham** [comment]
New version v0.7.4 has been released with this update
f47e2d8da41c43a48a364c37835c8d88140012d1
